### ISSUE TITLE
Compatibility of DoctrineVectorStore with doctrine migration

### ISSUE THREAD

**Issue by SebastienTouze** [theodo-group/LLPhant#48]
Hi o/

As the VectorType type is added to Doctrine on DoctrineVectorStore constructor, it is not available in DoctrineMigration which is not aware of this type. So using `bin/console make:migration` or equivalent `bin/console doctrine:migration:diff` result in error: ` Unknown column type "vector" requested.`

One option seems to move the type declaration to doctrine dbal config file, with consequence to make the VectorType always available to doctrine. This is mostly adding some config info on the readme and maybe remove the integration in DoctrineVectorStore class. 

If this proposition is OK for you I can open a PR

**Comment by SebastienTouze** [comment]
Example of config that seems to work 
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            vector: LLPhant\Embeddings\VectorStores\Doctrine\VectorType
        mapping_types:
            enum: string
            vector: vector
```

But I get an error on length not being define though it is defined in default DoctrineEmbeddingEntityBase I extend.

**Comment by chr-hertel** [comment]
Currently using `vector: array` as mapping type currently, but also still having issues with migrations.
For me it is regenerating the same migrations all over again

**Comment by arnaudgoulpeau** [comment]
Hi !

I used this bundle (mainly to get access to DQL functions) : https://packagist.org/packages/partitech/doctrine-pgvector
If you follow their docs about configuring the new type, you shouldn't have problems.
It works great on with doctrine/dbal 3.8 and doctrine/orm 2.19

Hope this helps

**Comment by bernard-ng** [comment]
```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            vector: LLPhant\Embeddings\VectorStores\Doctrine\VectorType
```

This package is not a [*symfony bundle.*](https://symfony.com/doc/current/bundles.html) thus the VectorType won't be provided automatically, you have to specify it in your project configuration *config/packages/doctrine.yaml* to fix the issue
